# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d051edf28b908b3cdbcadfb61d9a3b48d661a8e8e69ea938944f17505f809fce19f916e94f35b85dbf32500d2b6ed4ce7b2d8bf035f16068e59d7901286e554e

test:
  secret_key_base: 171129807f06ae18b13e03a05711ef6a1fc99e06f143a48931ea3eaabc479de96ffd32b32ea26978d85ef9e7ef4791b23a8bda1a20fddfb3b3ed458b65ef1ed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
